FROM amelia/dhparam:latest as dh
FROM nginx:mainline-alpine as nginx
FROM amelia/php:cli

LABEL maintainer="amelia@dorks.io"

# Add the www-data user
RUN set -x && addgroup -g 82 -S www-data && adduser -u 82 -D -S -G www-data www-data

# Install packages
RUN apk --update add supervisor php7-fpm \
    && rm -rf /var/cache/apk/* \
    && rm /etc/init.d/php-fpm7

# install nginx from the mainline image
COPY --from=nginx /etc/nginx/* /etc/nginx/
COPY --from=nginx /usr/sbin/nginx* /usr/sbin/
COPY --from=nginx /usr/lib/libssl* /usr/lib/
COPY --from=nginx /usr/lib/libcrypto* /usr/lib/

COPY --from=dh /etc/ssl/dhparam.pem /etc/nginx/dhparam.pem
COPY --from=dh /etc/ssl/snakeoil-cert.pem /etc/nginx/certs/certificate.pem
COPY --from=dh /etc/ssl/snakeoil-key.pem /etc/nginx/certs/privkey.pem

# Copy php/nginx/supervisor files
COPY files/supervisor/supervisor.conf /etc/supervisord.conf

COPY files/php-fpm/php-fpm.conf /etc/php7/php-fpm.conf
COPY files/php-fpm/www.conf /etc/php7/php-fpm.d/www.conf
COPY files/php-fpm/php.ini /etc/php7/conf.d/php.ini

COPY files/nginx/site.conf /etc/nginx/conf.d/site.conf
COPY files/nginx/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/log/nginx && \
    mkdir -p /var/cache/nginx && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /srv/code

EXPOSE 80 443

CMD ["supervisord", "-n", "-c", "/etc/supervisord.conf"]
