FROM amelia/dhparam:latest as dh
FROM nginx:mainline-alpine as nginx
FROM composer:latest as composer
FROM alpine:latest

LABEL maintainer="amelia@dorks.io"

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_NO_INTERACTION 1
ENV COMPOSER_HOME /usr/lib/composer
ENV COMPOSER_CACHE_DIR /var/cache/composer

# add the www-data user
RUN set -x \
    && addgroup -g 82 -S www-data \
    && adduser -u 82 -D -S -G www-data www-data \
    && apk --update add \
        ca-certificates \
        php7 \
        php7-cli \
        php7-curl \
        php7-gd \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-opcache \
        php7-openssl \
        php7-pdo_pgsql \
        php7-zip \
        php7-phar \
        php7-tokenizer \
        php7-fileinfo \
        php7-pcntl \
        php7-posix \
        php7-zlib \
        php7-iconv \
        php7-session \
        supervisor \
        php7-fpm \
    && update-ca-certificates \
    && rm -rf /var/cache/apk/* \
    && rm /etc/init.d/php-fpm7 \
    && mkdir -p /var/log/nginx \
    && mkdir -p /var/cache/nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# copy over composer
COPY --from=composer /usr/bin/composer /usr/bin

# install nginx from the mainline image
COPY --from=nginx /etc/nginx/* /etc/nginx/
COPY --from=nginx /usr/sbin/nginx* /usr/sbin/
COPY --from=nginx /usr/lib/libssl* /usr/lib/
COPY --from=nginx /usr/lib/libcrypto* /usr/lib/

# copy over dhparams and a snakeoil cert
COPY --from=dh /etc/ssl/dhparam.pem /etc/nginx/dhparam.pem
COPY --from=dh /etc/ssl/snakeoil-cert.pem /etc/nginx/certs/certificate.pem
COPY --from=dh /etc/ssl/snakeoil-key.pem /etc/nginx/certs/privkey.pem

# add the supervisor config
COPY files/supervisor/supervisor.conf /etc/supervisord.conf

# add fpm files
COPY files/php-fpm/php-fpm.conf /etc/php7/php-fpm.conf
COPY files/php-fpm/www.conf /etc/php7/php-fpm.d/www.conf
COPY files/php-fpm/php.ini /etc/php7/conf.d/20-extra.ini

# add custom nginx files
COPY files/nginx/site.conf /etc/nginx/conf.d/site.conf
COPY files/nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /srv/code

EXPOSE 80 443

CMD ["supervisord", "-n", "-c", "/etc/supervisord.conf"]
